apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: search-engine
spec:
  replicas: 1   # RabbitMQ's competing-consumers pattern means you CAN scale
                # this to 2+ replicas safely later if throughput needs it
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      enableServiceLinks: false
      containers:
        - name: indexer
          image: indexer:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: search-engine-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: search-engine-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: search-engine-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: search-engine-secrets
                  key: RABBITMQ_PASSWORD
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: search-engine-config
                  key: ELASTICSEARCH_URL